x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  server:
    image: judge0/judge0:latest
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "80:2358"
    security_opt:
      - apparmor:unconfined
    privileged: true
    <<: *default-logging
    restart: always

  worker:
    image: judge0/judge0:latest
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
      - /sys/fs/cgroup/cpu,cpuacct:/sys/fs/cgroup/cpu,cpuacct:rw
      - /sys/fs/cgroup/memory:/sys/fs/cgroup/memory:rw
      - /sys/fs/cgroup/cpuset:/sys/fs/cgroup/cpuset:rw
      - /sys/fs/cgroup/systemd:/sys/fs/cgroup/systemd:rw
    environment:
      - ISOLATE_CGROUP_SKIP_CONTROLLERS=cpuset
    privileged: true
    security_opt:
      - apparmor:unconfined
    <<: *default-logging
    restart: always

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always

volumes:
  data:
